/*
===============================================================================
 PRACTICE QUESTION 40: GUESS THE NUMBER GAME
===============================================================================
PROBLEM STATEMENT:
Write an interactive C program that generates a random number between 1 and 100.
The user gets 7 attempts to guess the correct number.
After each guess, provide feedback: "Too High!", "Too Low!", or "Correct!".

KEY CONCEPTS EXPLAINED IN COMMENTS:
1. srand(time(NULL)): Seeds the random number generator using the current system time 
   so that a truly different random number sequence is generated every time you run the program.
2. rand() % 100 + 1: Restricts the huge random number generated by rand() 
   to a clean range between 1 and 100.
===============================================================================
*/

#include <stdio.h>
#include <stdlib.h> // Required for rand() and srand()
#include <time.h>   // Required for time()

int main() {
    int secretNum, userGuess;
    int attempts = 0;
    const int MAX_ATTEMPTS = 7;

    /* 
      -------------------------------------------------------------------------
      STEP 1: SEEDING THE RANDOM NUMBER GENERATOR
      -------------------------------------------------------------------------
      Computers cannot generate truly random numbers on their own; they use a 
      formula. If we don't change the starting point (seed), rand() will produce 
      the exact same sequence of numbers every single time you launch the program.
      
      By passing 'time(NULL)' (current computer clock time in seconds) into 
      srand(), the starting point changes every second. This guarantees a 
      unique random number sequence for every game session.
    */
    srand(time(NULL));

    /* 
      -------------------------------------------------------------------------
      STEP 2: GENERATING THE SECRET NUMBER BETWEEN 1 AND 100
      -------------------------------------------------------------------------
      - rand() produces a large integer (e.g., 18467).
      - rand() % 100 gives the remainder when divided by 100, which restricts 
        the possible values to a range of 0 to 99.
      - Adding + 1 shifts the range up, changing it from (0 to 99) to (1 to 100).
    */
    secretNum = (rand() % 100) + 1;

    printf("=========================================\n");
    printf("   WELCOME TO 'GUESS THE NUMBER' GAME!   \n");
    printf("=========================================\n");
    printf("I have chosen a secret number between 1 and 100.\n");
    printf("You have %d attempts to guess it. Good luck!\n\n", MAX_ATTEMPTS);

    /* 
      -------------------------------------------------------------------------
      STEP 3: GAME LOOP (RUNS UNTIL ATTEMPTS EXHAUSTED)
      -------------------------------------------------------------------------
      The while loop keeps asking the user for inputs as long as their total 
      used attempts are less than the allowed maximum attempts (7).
    */
    while (attempts < MAX_ATTEMPTS) {
        printf("Attempt %d/%d - Enter your guess: ", attempts + 1, MAX_ATTEMPTS);
        
        // Validate user input to ensure they entered a valid integer
        if (scanf("%d", &userGuess) != 1) {
            printf("Invalid input! Please enter a valid number.\n");
            // Clear the invalid input from the input buffer
            while (getchar() != '\n');
            continue;
        }

        // Increment the attempt counter after a valid guess is made
        attempts++;

        /* 
          -------------------------------------------------------------------------
          STEP 4: EVALUATING THE USER'S GUESS
          -------------------------------------------------------------------------
          Compare the user's input with the generated secret number and provide 
          clear high/low feedback to steer their next guess.
        */
        if (userGuess == secretNum) {
            printf("\nCONGRATULATIONS! You guessed the correct number %d in %d attempts!\n", secretNum, attempts);
            break; // Exit the loop because the user won the game
        } 
        else if (userGuess > secretNum) {
            printf("Too High! Try a smaller number.\n\n");
        } 
        else {
            printf("Too Low! Try a larger number.\n\n");
        }
    }

    /* 
      -------------------------------------------------------------------------
      STEP 5: CHECKING FOR GAME OVER CONDITION
      -------------------------------------------------------------------------
      If the user used all 7 attempts and still hasn't matched the secret number, 
      display the game over message and reveal the secret number.
    */
    if (userGuess != secretNum) {
        printf("\nGAME OVER! You ran out of all %d attempts.\n", MAX_ATTEMPTS);
        printf("The secret number was: %d\n", secretNum);
    }

    printf("=========================================\n");
    return 0;
}
/*
===============================================================================
Output:
===============================================================================
=========================================
   WELCOME TO 'GUESS THE NUMBER' GAME!   
=========================================
I have chosen a secret number between 1 and 100.
You have 7 attempts to guess it. Good luck!

Attempt 1/7 - Enter your guess: 50
Too High! Try a smaller number.

Attempt 2/7 - Enter your guess: 25
Too High! Try a smaller number.

Attempt 3/7 - Enter your guess: 10
Too Low! Try a larger number.
Attempt 4/7 - Enter your guess: 16

CONGRATULATIONS! You guessed the correct number 16 in 4 attempts!
=========================================

*/